server:
  port: PORT
logging:
  level: LOG_LEVEL
database:
  name: DATABASE_NAME
  host: DATABASE_HOST
  user: DATABASE_USER
  password: DATABASE_PASSWORD
  port: DATABASE_PORT
  ssl: DATABASE_SLL
  connectionTimeoutInMilli: DATABASE_CONNECTION_TIMEOUT_IN_MILLI
  connection:
    max: DATABASE_CONNECTION_MAX
cache:
  host: REDIS_HOST
  port: REDIS_PORT
  ttl: REDIS_TTL
token:
  secret: AUTH_TOKEN
