services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB: fila-digital
      POSTGRES_PASSWORD: '123321'
      POSTGRES_USER: 'fila-digital-user'
    ports:
      - 5435:5432
    restart: on-failure:3
  redis:
    image: redis:latest
    command: redis-server
    volumes:
      - redis:/var/lib/redis
      - redis-config:/usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
    networks:
      - redis-network
volumes:
  redis:
  redis-config:
networks:
  redis-network:
    driver: bridge
