import {
  ColumnType,
  Generated,
  Insertable,
  Selectable,
  Updateable,
} from "kysely";

export interface Database {
  commerce: CommerceTable;
  queue: QueueTable;
  person: PersonTable;
  participants_queue: ParticipantsQueue;
}

export interface CommerceTable {
  // Columns that are generated by the database should be marked
  // using the `Generated` type. This way they are automatically
  // made optional in inserts and updates.
  id: Generated<string>;

  name: string;
  description: string | null;
  // You can specify a different type for each operation (select, insert and
  // update) using the `ColumnType<SelectType, InsertType, UpdateType>`
  // wrapper. Here we define a column `created_at` that is selected as
  // a `Date`, can optionally be provided as a `string` in inserts and
  // can never be updated:
  phone: string;
  document_id: string;
  owner_id: string;
  created_at: ColumnType<Date, string | undefined, never>;
  updated_at: ColumnType<Date, string | undefined, string>;
  open_at: ColumnType<Date, string | undefined, string>;
  closed_at: ColumnType<Date, string | undefined, string>;
  active: ColumnType<boolean, boolean | undefined, boolean>;
}

// You should not use the table schema interfaces directly. Instead, you should
// use the `Selectable`, `Insertable` and `Updateable` wrappers. These wrappers
// make sure that the correct types are used in each operation.
//
// Most of the time you should trust the type inference and not use explicit
// types at all. These types can be useful when typing function arguments.
export type Commerce = Selectable<CommerceTable>;
export type NewCommerce = Insertable<CommerceTable>;
export type CommerceUpdate = Updateable<CommerceTable>;

export interface QueueTable {
  id: Generated<string>;
  commerce_id: string | null;
  name: string;
  description: string | null;
  type: "ephemera" | "permanent";
  status: "open" | "closed";
  qrcode_token: string;
  created_at: ColumnType<Date, string | undefined, never>;
  updated_at: ColumnType<Date, string | undefined, string>;
  active: boolean;
}

export type Queue = Selectable<QueueTable>;
export type NewQueue = Insertable<QueueTable>;
export type QueueUpdate = Updateable<QueueTable>;

export interface PersonTable {
  id: Generated<string>;
  name: string;
  email: string;
  phone: string;
  password: string;
  commerce_id: string | null;
  queue_id: string | null;
  created_at: ColumnType<Date, string | undefined, never>;
  updated_at: ColumnType<Date, string | undefined, string>;
}

export type Person = Selectable<PersonTable>;
export type NewPerson = Insertable<PersonTable>;
export type PersonUpdate = Updateable<Partial<PersonTable>>;

export interface ParticipantsQueueTable {
  id: Generated<string>;
  queue_id: string | null;
  person_id: string | null;
  anonymous_id: string | null;
  position: number | null;
  created_at: ColumnType<Date, string | undefined, never> | null;
  updated_at: ColumnType<Date, string | undefined, string> | null;
  is_active: boolean;
}

export type ParticipantsQueue = Selectable<ParticipantsQueueTable>;
export type NewParticipantQueue = Insertable<ParticipantsQueue>;
export type QueuePartcipantUpdate = Updateable<Partial<ParticipantsQueue>>;
